//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sessao_1___OCE
{
    using System;
    using System.Collections.Generic;
    
    public partial class cidades
    {
        public int id { get; set; }
        public string cidade { get; set; }
        public int id_cidade { get; set; }
        public int id_usuario { get; set; }
    
        public virtual estados estados { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
